pipeline {
    agent any
    tools {
        maven 'maven-3.8.4'
        gradle 'gradle-8.14.2'
    }
    parameters {
        choice(name: 'build_tool',
               choices: ['maven', 'gradle'],
               description: 'Choose the build tool for this deployment'
        )
    }
    stages {
        stage('Build with Maven') {
            when {
                expression { params.build_tool == 'maven' }
            }
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Build with Gradle') {
            when {
                expression { params.build_tool == 'gradle' }
            }
            steps {
                sh './gradlew build'
            }
        }
    }
}