pipeline {
    agent any
    tools {
        maven 'maven-3.8.4'
        gradle 'gradle-8.14.2'
    }
    parameters {
        choice(name: 'build_tool',
               choices: ['maven', 'gradle'],
               description: 'Choose the build tool for this deployment'
        )
    }
        properties([
            promotions([
                [
                    name: 'QA Approved',
                    icon: 'star-gold',
                    conditions: [
                        selfPromotion(evenIfUnstable: false)
                    ]
                ],
                [
                    name: 'Deployed to PROD',
                    icon: 'star-blue',
                    conditions: [
                        manual('admin')
                    ],
                    actions: [
                        {
                            sh 'echo "Deploying to Production..."'
                        }
                    ]
                ]
            ])
        ])
    stages {
        stage('Build with Maven') {
            when {
                expression { params.build_tool == 'maven' }
            }
            steps {
            dir('01.CICD'){
                sh 'mvn clean package'
            }
            }
        }
        stage('Build with Gradle') {
            when {
                expression { params.build_tool == 'gradle' }
            }
            steps {
            dir('01.CICD'){
                sh 'chmod +x gradlew'
                sh './gradlew build'
            }
            }
        }
    }
}